# Site information
site_name: PhotoFF
site_description: A library for processing images in Python with CUDA support.
site_author: Beltrán Offerrall
repo_name: PhotoFF
repo_url: https://github.com/offerrall/photoff


# Theme configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - toc.integrate
    - navigation.tabs.sticky
    - navigation.top
    - hide:
        - toc.title
  palette:
    # Dark mode (default)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Light mode
    # Light mode alternative
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Dark mode

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: '__span'
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Navigation structure
nav:
  - Start: index.md
  - Learn: 
    - Basics: basics.md
    - Advanced: advanced.md
    - Installation: installation.md
  - API: api.md

# Plugins (optional but useful)
plugins:
  - search
  - minify:
      minify_html: true

# Footer links and information (optional)
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/offerrall/photoff
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/offerrall